### ISSUE TITLE
批量同步参数问题

### ISSUE THREAD

**Issue by houziyu** [CharellKing/ela#1]
你好，我想问一下参数使用问题，
比如我有5个索引 order_index、order_qa、order_nn、task_info、task_num
我想同步order* 以及 task* 得索引。但是同步order*的时候不需要同步order_nn索引的话。这个配置应该是怎么写

**Comment by quzhaojing** [comment]
index_pattern: "^(task.*|order(?!_nn).*)$"

**Comment by houziyu** [comment]
好的谢谢

**Comment by lianmeng0** [comment]
> index_pattern: "^(task._|order(?!_nn)._)$"

![image](https://github.com/user-attachments/assets/7cc51bc5-b686-4fee-bbb5-d1cab2fa6089)

Could you please tell me where the error in my settings is? I'm trying to match the migrated index based on the date's regular expression, but the configuration keeps giving me errors.
```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/CharellKing/ela/service.(*BulkMigrator).WithPatternIndexes(0xc00011ade0, {0xc000142300, 0x21})
        D:/code/ela/service/bulkmigrator.go:195 +0x285
github.com/CharellKing/ela/service.NewTaskWithES({0x1a19710, 0x2964820}, 0xc000159180, {0x1a1c5b0, 0xc00020a7b0}, {0x1a1c548, 0xc0001e1338})
        D:/code/ela/service/task.go:31 +0x5ba
github.com/CharellKing/ela/service.(*TaskMgr).Run(0xc000118c00, {0x1a19710, 0x2964820})
        D:/code/ela/service/taskmgr.go:49 +0x188
main.main()
        D:/code/ela/main.go:40 +0x1bc
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/CharellKing/ela/service.(*BulkMigrator).WithPatternIndexes(0xc000130d80, {0xc00013e360, 0x21})
        D:/code/ela/service/bulkmigrator.go:195 +0x285
github.com/CharellKing/ela/service.NewTaskWithES({0x1a19710, 0x2964820}, 0xc000155180, {0x1a1c5b0, 0xc000250798}, {0x1a1c548, 0xc0001e33c8})
        D:/code/ela/service/task.go:31 +0x5ba
github.com/CharellKing/ela/service.(*TaskMgr).Run(0xc000134c80, {0x1a19710, 0x2964820})
```
thanks!

**Comment by quzhaojing** [comment]
the tool is developed by golang. so your regular expression should comply with golang syntax.

**Comment by quzhaojing** [comment]
just replace "index_pattern:"www_collection_miniprogram_zpzy_*" with index_pattern:"www_collection_miniprogram_zpzy_.\*"

**Comment by quzhaojing** [comment]
you can use the online tool to check your regex expression: https://www.akto.io/tools/go-regex-tester

**Comment by quzhaojing** [comment]
@lianmeng0 also you  need  upgrade to v0.0.6

**Comment by lianmeng0** [comment]
> @lianmeng0 also you need upgrade to v0.0.6

I have identified an issue with the 'parallelism' parameter. When utilized in conjunction with the 'indexpattern' parameter, if the parallelism setting surpasses the number of indexes, it leads to a server memory overflow, resulting in the process halting. If the parallelism setting does not exceed the number of indexes (for instance, 2), only 2 indexes will be migrated and the migration will not proceed further. It will not migrate all the indexes that match the regular expression of the 'indexpattern' parameter.

**Comment by lianmeng0** [comment]
> @lianmeng0 also you need upgrade to v0.0.6

I have identified an issue with the 'parallelism' parameter. When utilized in conjunction with the 'indexpattern' parameter, if the parallelism setting surpasses the number of indexes, it leads to a server memory overflow, resulting in the process halting. If the parallelism setting does not exceed the number of indexes (for instance, 2), only 2 indexes will be migrated and the migration will not proceed further. It will not migrate all the indexes that match the regular expression of the 'indexpattern' parameter.

**Comment by CharellKing** [comment]
There are default 1000 records for every scroll. If you have 1000 parallel goroutine,  1000000 records could be  loaded in the same time. if every record's size is 1KB, it will cost 1G memory.

**Comment by quzhaojing** [comment]
The server keeps the scroll for 10 minutes.  When many scrolls are created at the same time, the es server will overflow memory.  I recommend that the parallelism is kept same with the CPU core amount of the host where the ela tool is deployed.

**Comment by lianmeng0** [comment]
> 服务器将滚动条保持 10 分钟。当同时创建多个滚动时，es 服务器将溢出内存。我建议并行度与部署 ela 工具的主机的 CPU 核心数量保持一致。

What I mean is that I have 100 indexes to migrate, but when I set the parameter 'indexpattern' to 2, only the first 2 indexes will be migrated, and the remaining 98 will not be migrated anymore

**Comment by quzhaojing** [comment]
index pattern which is used to filter index by regex regular to sync, source index is same with target index. if you want to sync all indexes, you should set 'indexpattern' to "\.*"

**Comment by lianmeng0** [comment]
> 索引模式，用于按正则表达式规则过滤索引以同步，源索引与目标索引相同。如果要同步所有索引，应将“indexpattern”设置为“.*”

![image](https://github.com/user-attachments/assets/13cd5d5d-16e0-4005-95cf-df9617db5faf)
But I don't want to synchronize all the indexes, I just want to synchronize the indexes that match the same type of regularization mentioned above. But according to the above settings, it will only synchronize the indexes of July 15th and July 16th, and the indexes of later dates will not be synchronized

**Comment by quzhaojing** [comment]
you can ask chatgpt to construct regex expression as your rule.

**Comment by quzhaojing** [comment]
or you can split multiple tasks with regex expression.

**Comment by lianmeng0** [comment]
您好！有个参数希望和您对一下。配置文件中的force参数使用false时，迁移索引依然还是强制迁移索引的参数，例如源索引 的分片和副本数分别为4、1迁移到目标集群时索引模板修改为2、2，但是迁移后依然是4、1好像并没有走模板

**Comment by quzhaojing** [comment]
the newest version will fix the problem.

**Comment by quzhaojing** [comment]
@lianmeng0  you can try v1.2.3

**Comment by lianmeng0** [comment]
> @lianmeng0 you can try v1.2.3

您好！经过验证好像这个参数：force: true并没有修改成功，还是一样。无法去根据目标集群的模板去创建索引，源索引的主分为4，副本为1，目标集群的模板设置索引的主片为2，副本为1，但是迁移后的索引依然是主片4，副本1，似乎force: false并没有效果

**Comment by quzhaojing** [comment]
now when you use "force = true", ela will copy source index settings to target index settings.

**Comment by quzhaojing** [comment]
if you want to use index template. you can remove the target index manually and then run ela tool with "force = false"
