### ISSUE TITLE
可添加条件迁移

### ISSUE THREAD

**Issue by lianmeng0** [CharellKing/ela#10]
Hi ! 
        迁移索引数据时可以根据query条件去迁移，例如有个150亿条数据、大小是7T的索引，其中有很多数据都是不要的，想要通过query查出需要的数据然后导入到新集群中去

**Comment by quzhaojing** [comment]
it will be supported in the future.

**Comment by lianmeng0** [comment]
你好！还有一个问题，就是配置文件中写多个tasks,执行过程中只能一个一个的进行，无法多个任务同时进行。--tasks all参数可以添加吗？

**Comment by quzhaojing** [comment]
this feature will be supported in the future

**Comment by quzhaojing** [comment]
now you can run all tasks by such command "./ela --config ./config.yaml --tasks"

**Comment by quzhaojing** [comment]
use newest version, support query paramethers only with the configure:   query: '{"bool":{"should":[{"match":{"order_no":"202003131209120999"}},{"match":{"order_no":"22222222222222222"}}]}}}'

**Comment by lianmeng0** [comment]
> use newest version, support query paramethers only with the configure: query: '{"bool":{"should":[{"match":{"order_no":"202003131209120999"}},{"match":{"order_no":"22222222222222222"}}]}}}'

该如何配置配置文件或者这个query是写在配置文件的外部，您可以更新一下readme.md文件吗？这将非常感谢！

**Comment by quzhaojing** [comment]
configure file. it will be updated later.

**Comment by lianmeng0** [comment]
> > use newest version, support query paramethers only with the configure: query: '{"bool":{"should":[{"match":{"order_no":"202003131209120999"}},{"match":{"order_no":"22222222222222222"}}]}}}'
> 
> 该如何配置配置文件或者这个query是写在配置文件的外部，您可以更新一下readme.md文件吗？这将非常感谢！

使用最新版的会有400的报错，必须要添加query？
```
{"file":"D:/go/pkg/mod/github.com/!charell!king/ela-lib@v1.1.4/service/task/migrator.go:895","func":"github.com/CharellKing/ela-lib/service/task.(*Migrator).search.(*Migrator).searchSingleSlice.func3.2","level":"error","msg":"searchSingleSlice error: status: 400 Bad Request, body: [400 Bad Request] {\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"query malformed, empty clause found at [1:11]\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"query malformed, empty clause found at [1:11]\"},\"status\":400}\ngithub.com/CharellKing/ela-lib/pkg/es.formatError\n\tD:/go/pkg/mod/github.com/!charell!king/ela-lib@v1.1.4/pkg/es/es0.go:211\ngithub.com/CharellKing/ela-lib/pkg/es.(*V7).NewScroll\n\tD:/go/pkg/mod/github.com/!charell!king/ela-lib@v1.1.4/pkg/es/es7.go:120\ngithub.com/CharellKing/ela-lib/service/task.(*Migrator).search.(*Migrator).searchSingleSlice.func3.2\n\tD:/go/pkg/mod/github.com/!charell!king/ela-lib@v1.1.4/service/task/migrator.go:885\ngithub.com/CharellKing/ela-lib/service/task.(*Migrator).search.(*Migrator).searchSingleSlice.func3\n\tD:/go/pkg/mod/github.com/!charell!king/ela-lib@v1.1.4/service/task/migrator.go:903\nruntime.goexit\n\tD:/Program Files/Go/src/runtime/asm_amd64.s:1700","sourceEsVersion":"7.15.1","sourceObject":"www_yqt_warningsendrecordindex_20210418","targetEsVersion":"7.15.1","targetObject":"www_yqt_warningsendrecordindex_20210418","taskAction":"sync","taskId":"1ad3c451-65ad-4f6c-a96b-12413a5dc64f","taskName":"log","taskProgress":"0/1","time":"2024-11-15T19:07:52+08:00"}
```
在不指定query时，不应该会跳出这种错误的才是

**Comment by quzhaojing** [comment]
you can try v1.2.3; you can get the example about 'query' parameters from this article: https://github.com/CharellKing/ela/blob/main/manual/en/03-Stock%20Data%20Migration.md
