### ISSUE TITLE
支持es2迁移到es8.x吗？

### ISSUE THREAD

**Issue by minkiki** [CharellKing/ela#11]
尝试了一下es2会报错，能支持es2迁移到es8.x吗？

**Comment by quzhaojing** [comment]
now ela tools support the elasticsearch versions above 5.x.

**Comment by quzhaojing** [comment]
now we have no plan to support es2

**Comment by quzhaojing** [comment]
@minkiki  now we have supported all the elasticsearch below elasticsearch5, included es2.
