### ISSUE TITLE
need  supports  local save for es 8

### ISSUE THREAD

**Issue by camuselliot** [CharellKing/ela#2]
supports local saving for es8

**Comment by camuselliot** [comment]
need  support full backup

**Comment by quzhaojing** [comment]
why need to local saving, you can use elasticsearch dump tool; https://github.com/elasticsearch-dump/elasticsearch-dump

**Comment by quzhaojing** [comment]
@camuselliot  now have supported to import data from local file and export data to local file.

**Comment by quzhaojing** [comment]
you can get it from README.
