### ISSUE TITLE
执行的过程中，有参数可以打印执行日志吗

### ISSUE THREAD

**Issue by Niidy** [CharellKing/ela#5]

**Comment by quzhaojing** [comment]
you can set the log level to show the logs; now the log default level is "info"; it means that these level logs will be printed; such as  info、warn、error.

**Comment by CharellKing** [comment]
![image](https://github.com/user-attachments/assets/509b2984-0cf9-400d-a59b-ef27681f64e6)

**Comment by quzhaojing** [comment]
![image](https://github.com/user-attachments/assets/c99ec58d-b9d0-4120-af08-f62ff39e6013)

**Comment by quzhaojing** [comment]
or you can set the level configure field in configure file. but you need use v0.0.8.
